const UPDATE_USER_DATA = `UPDATE_USER_DATA`;
const CLEAR_USER = `CLEAR_USER`;
const TOGGLE_BATTLE_BUTTON = `TOGGLE_BATTLE_BUTTON`;
const TOGGLE_RESTART_BUTTON = `TOGGLE_RESTART_BUTTON`;
const UPDATE_USER_REPOSITORIES = `UPDATE_USER_REPOSITORIES`;
const CALCULATE_USERS_SCORE = `CALCULATE_USERS_SCORE`;
const RESET_ALL_USERS = `RESET_ALL_USERS`;
const CLEAR_SCORES = `CLEAR_SCORES`;
const TRIGGER_RESTART = `TRIGGER_RESTART`;

export {
  UPDATE_USER_DATA,
  CLEAR_USER,
  TOGGLE_BATTLE_BUTTON,
  TOGGLE_RESTART_BUTTON,
  UPDATE_USER_REPOSITORIES,
  CALCULATE_USERS_SCORE,
  RESET_ALL_USERS,
  CLEAR_SCORES,
  TRIGGER_RESTART
};

