const TODOS_FILTER_ALL = `TODOS_FILTER_ALL`;
const TODOS_FILTER_COMPLETED = `TODOS_FILTER_COMPLETED`;
const TODOS_FILTER_PROGRESS = `TODOS_FILTER_PROGRESS`;

const TODOS_DEFAULT_COLOR = `#ed143d`;

export {
  TODOS_FILTER_ALL,
  TODOS_FILTER_COMPLETED,
  TODOS_FILTER_PROGRESS,
  TODOS_DEFAULT_COLOR,
};
