const TODOS_FILTER_COMPLETED = `TODOS_FILTER_COMPLETED`;
const TODOS_FILTER_NON_COMPLETED = `TODOS_FILTER_NON_COMPLETED`;
const TODOS_FILTER_ALL = `TODOS_FILTER_ALL`;

export { TODOS_FILTER_COMPLETED, TODOS_FILTER_NON_COMPLETED, TODOS_FILTER_ALL };
